import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-waves rounded-br-full max-w-[730px] w-full md:min-h-[1024px] min-h-[690px] absolute top-0 left-0"></div>
      <section className="container px-3 py-5 z-10 relative">
      <Navbar/>

      <header className="md:mt-[200px] mt-8 max-w-[540px] w-full">
        <h1 className="text-white text-3xl">- Olá, eu sou o <b className="text-primary text-3xl">Braian</b>, <b className="text-primary text-3xl">desenvolvedor web</b> e <b className="text-primary text-3xl">Freelancer</b></h1>
        <p className="my-[30px] text-sm text-white max-w-[370px] w-full">Eu resolvo seus problemas através do código. Criando sempre o que você estava esperando.</p>

        <div className="flex items-center">
          <button className="transition p-3 max-w-[236px] w-full border-0 bg-primary hover:bg-darker text-black/80 hover:text-white text-center rounded-md font-bold button-border">Download CV</button>
        </div>

        <div className="flex flex-col items-center w-max gap-8 slide-top">
        <span className="scroll">Scroll</span>
        <svg className="pulse" width="16" height="20" viewBox="0 0 16 20" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path d="M6.98486 9.74365L0.344238 3.10303C-0.114746 2.64404 -0.114746 1.90186 0.344238 1.44775L1.44775 0.344238C1.90674 -0.114746 2.64893 -0.114746 3.10303 0.344238L7.81006 5.05127L12.5171 0.344238C12.9761 -0.114746 13.7183 -0.114746 14.1724 0.344238L15.2856 1.44287C15.7446 1.90186 15.7446 2.64404 15.2856 3.09814L8.64502 9.73877C8.18604 10.2026 7.44385 10.2026 6.98486 9.74365ZM8.64502 19.1187L15.2856 12.478C15.7446 12.019 15.7446 11.2769 15.2856 10.8228L14.1821 9.71924C13.7231 9.26025 12.981 9.26025 12.5269 9.71924L7.81494 14.4214L3.10791 9.71435C2.64893 9.25537 1.90674 9.25537 1.45264 9.71435L0.344238 10.8179C-0.114746 11.2769 -0.114746 12.019 0.344238 12.4731L6.98486 19.1138C7.44385 19.5776 8.18604 19.5776 8.64502 19.1187Z" fill="#FDFDFD"/>
        </svg>
        </div>
    

      </header>
     

      </section>
     
    </div>
  )
}

export default Home
